#!/bin/sh

/bin/sh testP  ; X1=$?
/bin/sh testSE ; X2=$?
/bin/sh testTE ; X3=$?
/bin/sh testTh ; X4=$?
/bin/sh testC  ; X5=$?
/bin/sh testSW ; X6=$?
/bin/sh testR  ; X7=$?

TOTAL=$[$X1 + $X2 + $X3 + $X4 + $X5 + $X6 + $X7]
echo "Total number of simple tests that failed: $TOTAL"

if [ "$TOTAL" = "0" ];
then exit 0
else exit 1
fi
