#!/bin/sh

clear
echo SIMPLE TEST. NO OVERLOADING
cd simple
/bin/sh testAll; X0=$?
cd ..
echo OVERLOADING TEST SET
/bin/sh testP  ; X1=$?
/bin/sh testSE ; X2=$?
/bin/sh testTE ; X3=$?
/bin/sh testM  ; X4=$?
/bin/sh testTh ; X5=$?
/bin/sh testC  ; X6=$?
/bin/sh testSW ; X7=$?
/bin/sh testR  ; X8=$?
/bin/sh testTC ; X9=$?

TOTAL=$[$X0 + $X1 + $X2 + $X3 + $X4 + $X5 + $X6 + $X7 + $X8 + $X9]
echo "Test failures: $TOTAL"

if [ "$TOTAL" = "0" ];
then exit 0
else exit 1
fi
