module GCbug where

main = {- length-} (concat (concat top10))

top10 :: [[String]]
top10 = -- top 40, 17 februari 2002
    [ [ "1", "Shakira", "Whenever Wherever" ]
      , [ "2", "Marco en Sita", "Lopen op het water" ]
      , [ "3", "Pink", "Get the Party Started" ]
      , [ "4", "Within Temptation", "Ice Queen" ]
      , [ "5", "Linkin Park", "In the End" ]
      , [ "6", "Gigi d'Agostino", "L'Amour Toujours" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "2", "Marco en Sita", "Lopen op het water" ]
      , [ "3", "Pink", "Get the Party Started" ]
      , [ "4", "Within Temptation", "Ice Queen" ]
      , [ "5", "Linkin Park", "In the End" ]
      , [ "6", "Gigi d'Agostino", "L'Amour Toujours" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "2", "Marco en Sita", "Lopen op het water" ]
      , [ "3", "Pink", "Get the Party Started" ]
      , [ "4", "Within Temptation", "Ice Queen" ]
      , [ "5", "Linkin Park", "In the End" ]
      , [ "6", "Gigi d'Agostino", "L'Amour Toujours" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "2", "Marco en Sita", "Lopen op het water" ]
      , [ "3", "Pink", "Get the Party Started" ]
      , [ "4", "Within Temptation", "Ice Queen" ]
      , [ "5", "Linkin Park", "In the End" ]
      , [ "6", "Gigi d'Agostino", "L'Amour Toujours" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "2", "Marco en Sita", "Lopen op het water" ]
      , [ "3", "Pink", "Get the Party Started" ]
      , [ "4", "Within Temptation", "Ice Queen" ]
      , [ "5", "Linkin Park", "In the End" ]
      , [ "6", "Gigi d'Agostino", "L'Amour Toujours" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "2", "Marco en Sita", "Lopen op het water" ]
      , [ "3", "Pink", "Get the Party Started" ]
      , [ "4", "Within Temptation", "Ice Queen" ]
      , [ "5", "Linkin Park", "In the End" ]
      , [ "6", "Gigi d'Agostino", "L'Amour Toujours" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "8", "Nickelback", "How You Remind Me" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      , [ "7", "Nelly Furtado", "Shit on the Radio" ]
      , [ "9", "Alaueotueotueasueaaueonis Morissette", "Hands Clean" ]
      ]
