/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package helium-1.9 */
#ifndef VERSION_helium
#define VERSION_helium "1.9"
#endif /* VERSION_helium */
#ifndef MIN_VERSION_helium
#define MIN_VERSION_helium(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_helium */

/* package Top-1.9 */
#ifndef VERSION_Top
#define VERSION_Top "1.9"
#endif /* VERSION_Top */
#ifndef MIN_VERSION_Top
#define MIN_VERSION_Top(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_Top */

/* package base-4.13.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.13.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  13 || \
  (major1) == 4 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package containers-0.6.2.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.2.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_containers */

/* package directory-1.3.6.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package llvm-hs-pretty-0.9.0.0 */
#ifndef VERSION_llvm_hs_pretty
#define VERSION_llvm_hs_pretty "0.9.0.0"
#endif /* VERSION_llvm_hs_pretty */
#ifndef MIN_VERSION_llvm_hs_pretty
#define MIN_VERSION_llvm_hs_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_llvm_hs_pretty */

/* package llvm-hs-pure-9.0.0 */
#ifndef VERSION_llvm_hs_pure
#define VERSION_llvm_hs_pure "9.0.0"
#endif /* VERSION_llvm_hs_pure */
#ifndef MIN_VERSION_llvm_hs_pure
#define MIN_VERSION_llvm_hs_pure(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_llvm_hs_pure */

/* package lvmlib-1.9 */
#ifndef VERSION_lvmlib
#define VERSION_lvmlib "1.9"
#endif /* VERSION_lvmlib */
#ifndef MIN_VERSION_lvmlib
#define MIN_VERSION_lvmlib(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_lvmlib */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package network-2.6.3.6 */
#ifndef VERSION_network
#define VERSION_network "2.6.3.6"
#endif /* VERSION_network */
#ifndef MIN_VERSION_network
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 3)
#endif /* MIN_VERSION_network */

/* package parsec-3.1.14.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.14.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 14)
#endif /* MIN_VERSION_parsec */

/* package process-1.6.9.0 */
#ifndef VERSION_process
#define VERSION_process "1.6.9.0"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 9)
#endif /* MIN_VERSION_process */

/* package rhodium-0.1.0.0 */
#ifndef VERSION_rhodium
#define VERSION_rhodium "0.1.0.0"
#endif /* VERSION_rhodium */
#ifndef MIN_VERSION_rhodium
#define MIN_VERSION_rhodium(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_rhodium */

/* package template-haskell-2.15.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.15.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  15 || \
  (major1) == 2 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */

/* package text-1.2.4.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */

/* package unbound-generics-0.4.1 */
#ifndef VERSION_unbound_generics
#define VERSION_unbound_generics "0.4.1"
#endif /* VERSION_unbound_generics */
#ifndef MIN_VERSION_unbound_generics
#define MIN_VERSION_unbound_generics(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_unbound_generics */

/* package wl-pprint-1.2.1 */
#ifndef VERSION_wl_pprint
#define VERSION_wl_pprint "1.2.1"
#endif /* VERSION_wl_pprint */
#ifndef MIN_VERSION_wl_pprint
#define MIN_VERSION_wl_pprint(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_wl_pprint */

/* tool alex-3.2.4 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.2.4"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */

/* tool gcc-9 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "9"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.8.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.8.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.8.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.8.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.23.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.23.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  23 || \
  (major1) == 2 && (major2) == 23 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool happy-1.19.11 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.19.11"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 11)
#endif /* MIN_TOOL_VERSION_happy */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.8.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.8.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.34 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.34"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  34 || \
  (major1) == 2 && (major2) == 34 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "helium-1.9-HHxlspLsk1BBlf7J4m3RNX"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "helium-1.9-HHxlspLsk1BBlf7J4m3RNX"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.9"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
